# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Creo que así debería ser la conexión a la DB local
#spring.datasource.url=jdbc:postgresql://localhost:5432/donaciones
#spring.datasource.username=postgres
#spring.datasource.password=donaciones
#spring.datasource.driver-class-name=org.postgresql.Driver


#Creo así debería ser la conexión a la DB de Render
spring.datasource.url=jdbc:postgresql://dpg-d8lkjqpo3t8c73e8ged0-a.oregon-postgres.render.com:5432/donacionesdb
spring.datasource.username=donacionesdb_user
spring.datasource.password=9LHjaJsyC7uYbLIbJ8EvkKqgoCxFBAjz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
#Pruebo hacer que la base se genere sola
#spring.jpa.generete-ddl.true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

# Opcional
spring.jpa.properties.hibernate.format_sql=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

## Metrics
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=31ee0651f3619482f7057194b393e557
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com